-- Hanh's Log's own Supabase project (session 4) starts with an empty public
-- schema; everything in it is created by supabase/migrations. The tests
-- build: Supabase shim -> this (empty) baseline -> migrations.
-- Wanderlog's old schema snapshot is kept in supabase/archive/wanderlog-db/.
